name: build-package

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-client:
    needs: build-bot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        
      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@peoplegeist'
      
      - name: Cache node_modules 📦
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies 👨🏻‍💻
        run: npm ci

      - name: Build zerossl-renewal-client 🏗️
        run: npm run build

      - name: test npm package NPM 🔬
        run: npm test
        env:
          CERT_DOMAIN: test-api.peoplegeist.com
          AZURE_CLIENT_ID: ${{ secrets.AZURE_WESTEUROPE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_WESTEUROPE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZ_STORAGE_ACCOUNT_NAME: devpeoplegeist
          AZ_STORAGE_CONTAINER: certs

      - name: Publish npm package NPM 📚
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: false
  
  build-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WESTEUROPE_CREDENTIALS }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: peoplegeist.azurecr.io
          username: ${{ secrets.AZURE_WESTEUROPE_CLIENT_ID }}
          password: ${{ secrets.AZURE_WESTEUROPE_CLIENT_SECRET }}

      - name: Build, tag, and push image to AzureCR 
        id: build-image
        env:
          ACR_REGISTRY: peoplegeist.azurecr.io
          ACR_REPOSITORY: zerossl-certrenewal-bot
          IMAGE_TAG: ${{ github.sha }}_${{ steps.date.outputs.date }}
        run: |
          docker build -t $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG ./bot/
          docker push $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
          echo "image=$ACR_REGISTRY\/$ACR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: run bot
        run: docker run -e ZEROSSL_EMAIL=admin@peoplegeist.com -e CERT_DOMAIN=test-api.peoplegeist.com \
          -e AZURE_CLIENT_ID=${{ secrets.AZURE_WESTEUROPE_CLIENT_ID }} \
          -e AZURE_CLIENT_SECRET=${{ secrets.AZURE_WESTEUROPE_CLIENT_SECRET }} \
          -e AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }} \
          -e AZ_STORAGE_CONTAINER=devpeoplegeist \
          -e AZ_STORAGE_ACCOUNT_NAME=certs zerossl-certrenewal-bot:${{ github.sha }}
